name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      #Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      #Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      #Logowanie do Dockerhuba
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}


      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/maciub/zad1
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      #Zbudowanie i wypchniecie obrazu na Dockerhuba
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,src=docker.io/maciub/dockerrepo/zad1:cache
          cache-to: type=registry,dest=docker.io/maciub/dockerrepo/zad1:cache
          platforms: linux/arm64/v8,linux/amd64 
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}


      - name: Build and push to ghcr.io
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          image_tag: ${{steps.meta.outputs.tags}}
      
